import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Paper, Typography } from "@material-ui/core";
import { Header } from "../components/Header";
import { Post } from "../components/Post";
import { LeftMenu } from "../components/LeftMenu";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextNews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className = {styles.wrapper}>
        <div className="leftSite">
          <LeftMenu/>
        </div>
        <div className={styles.content}>
          <div className={styles.container}>
            <Post />
            <Post />
            <Post />
          </div>
        </div>
        <div className="rightSite"></div>
      </div>
    </div>
  );
}
